#!/usr/bin/env python
# patchxbe.py - Patch PE subsystem to Xbox (14), run imagebld, then inject
# D3D8/XGRAPHC library version entries so CXBX-Reloaded enables D3D8 HLE.
#
# Usage: patchxbe.py <exe_path> <xbe_out_path>

import sys
import os
import struct
import shutil
import subprocess

exe_path = sys.argv[1]
xbe_path = sys.argv[2]

# ── Step 1: Patch PE subsystem to Xbox (14) ──────────────────────────────

with open(exe_path, 'rb') as f:
    data = bytearray(f.read())

pe_offset = struct.unpack_from('<I', data, 0x3C)[0]

if data[pe_offset:pe_offset+4] != b'PE\0\0':
    print("ERROR: Not a valid PE file")
    sys.exit(1)

subsystem_offset = pe_offset + 24 + 68
old_subsystem = struct.unpack_from('<H', data, subsystem_offset)[0]
print("Original subsystem: %d" % old_subsystem)

struct.pack_into('<H', data, subsystem_offset, 14)
print("Patched subsystem to: 14 (Xbox)")

temp_exe = exe_path + '.xbox.tmp'
with open(temp_exe, 'wb') as f:
    f.write(data)

# ── Step 1b: Strip KERNEL32.dll import descriptor ────────────────────────
# libcd.lib pulls in RtlUnwind from KERNEL32 via SEH. imagebld rejects any
# PE that imports from Win32 DLLs. We zero out the KERNEL32 import descriptor
# so the import table only contains xboxkrnl.exe entries.

with open(temp_exe, 'rb') as f:
    pdata = bytearray(f.read())

pe_off = struct.unpack_from('<I', pdata, 0x3C)[0]
opt_off = pe_off + 24
# Import table RVA and size from data directory entry 1
import_rva  = struct.unpack_from('<I', pdata, opt_off + 104)[0]
import_size = struct.unpack_from('<I', pdata, opt_off + 108)[0]

# Find the section that contains the import table to convert RVA -> file offset
num_sections = struct.unpack_from('<H', pdata, pe_off + 6)[0]
sections_off = opt_off + struct.unpack_from('<H', pdata, opt_off - 2 + 2)[0]  # SizeOfOptionalHeader
sections_off = pe_off + 24 + struct.unpack_from('<H', pdata, pe_off + 20)[0]

def rva_to_offset(rva):
    for i in range(num_sections):
        s = sections_off + i * 40
        vaddr = struct.unpack_from('<I', pdata, s + 12)[0]
        vsize = struct.unpack_from('<I', pdata, s + 16)[0]
        raw   = struct.unpack_from('<I', pdata, s + 20)[0]
        if vaddr <= rva < vaddr + vsize:
            return raw + (rva - vaddr)
    return None

import_off = rva_to_offset(import_rva)
if import_off is not None:
    # Walk import descriptors (20 bytes each, terminated by all-zero entry)
    pos = import_off
    while True:
        desc = pdata[pos:pos+20]
        if desc == b'\x00' * 20:
            break
        name_rva = struct.unpack_from('<I', desc, 12)[0]
        name_off = rva_to_offset(name_rva)
        if name_off is not None:
            dll_name = pdata[name_off:name_off+32].split(b'\x00')[0].decode('ascii', errors='replace')
            if dll_name.upper() == 'KERNEL32.DLL':
                print("Zeroing KERNEL32.dll import descriptor at offset 0x%X" % pos)
                pdata[pos:pos+20] = b'\x00' * 20
        pos += 20

with open(temp_exe, 'wb') as f:
    f.write(pdata)
print("KERNEL32 import descriptor stripped.")

# ── Step 2: Run imagebld ─────────────────────────────────────────────────

# Prefer the same XDK imagebld used by build_xbox.bat. Mixing the 5558 build
# chain with the 5849 image builder can produce confusing dashboard metadata.
imagebld_candidates = [
    os.environ.get('IMAGEBLD', ''),
    os.path.join(os.environ.get('XDK_ROOT', ''), 'bin', 'imagebld.exe'),
    r'C:\XDK_5558\XDK\xbox\bin\imagebld.exe',
    r'C:\XDK\xbox\bin\imagebld.exe',
]
imagebld = None
for _candidate in imagebld_candidates:
    if _candidate and os.path.isfile(_candidate):
        imagebld = _candidate
        break
if imagebld is None:
    print("ERROR: imagebld.exe not found")
    sys.exit(1)
cmd = [imagebld, '/IN:' + temp_exe, '/OUT:' + xbe_path]
cmd.append('/TESTNAME:Star Wars Dark Forces')
# Use All-Star Baseball 2003's retail TitleID (AC-002). It is obscure but
# Xbox 360 backwards-compatible, which lets this port be tested there after
# original Xbox validation.
cmd.append('/TESTID:0x41430002')
cmd.append('/STACK:0x40000')
cmd.append('/TESTMEDIATYPES:0xFFFFFFFF')

# Dashboard/title assets. imagebld wants XPR-format images; the .xbx files in
# TheForceEngine/XboxAssets are XPRs generated by the XDK bundler.
_script_dir = os.path.dirname(os.path.abspath(__file__))
for _icon in [
    os.path.join('TheForceEngine', 'XboxAssets', 'titleimage.xbx'),
    'xbox_icon.xbx',
    os.path.join('TheForceEngine', 'xbox_icon.xbx'),
    'xbox_icon.bmp',
    os.path.join('TheForceEngine', 'xbox_icon.bmp'),
]:
    _p = os.path.join(_script_dir, _icon)
    if os.path.isfile(_p):
        cmd.append('/TITLEIMAGE:' + _p)
        break

for _icon in [
    os.path.join('TheForceEngine', 'XboxAssets', 'saveimage.xbx'),
    'xbox_saveimage.xbx',
    os.path.join('TheForceEngine', 'xbox_saveimage.xbx'),
]:
    _p = os.path.join(_script_dir, _icon)
    if os.path.isfile(_p):
        cmd.append('/DEFAULTSAVEIMAGE:' + _p)
        break

print("Running: " + ' '.join(cmd))
result = subprocess.call(cmd)

os.remove(temp_exe)

if result != 0:
    print("imagebld failed with code %d" % result)
    sys.exit(result)

print("XBE created: " + xbe_path)

# ── Step 3: Inject D3D8 + XGRAPHC library version entries ────────────────
# Legacy step from the VS2005 + XDK 5849 era when we linked d3d8-xbox.lib
# (a 3.5 KB stub that imagebld didn't tag as 'D3D8' in the XBE library
# table, so CXBX-Reloaded's HLE couldn't activate).
#
# With the current VC71 + XDK 5558 toolchain we link the full d3d8.lib /
# xgraphics.lib, which imagebld already enters into the table as 'D3D8'
# and 'XGRAPHC'. Injecting again produces DUPLICATE entries that confuse
# CXBX-R's HLE-pattern matching for adjacent libraries (DSOUND in
# particular).
#
# Match OpenJKDF2's known-good patchxbe.py: skip by default. Re-enable via
# `set PATCHXBE_INJECT_LIBS=1` only if a future build chain regresses.

if os.environ.get('PATCHXBE_INJECT_LIBS', '0') != '1':
    print("Skipping D3D8/XGRAPHC library injection (real D3D8 linked from XDK 5558).")
    sys.exit(0)

print("Injecting D3D8/XGRAPHC library version entries...")

with open(xbe_path, 'rb') as f:
    xbe = bytearray(f.read())

base_addr = struct.unpack_from('<I', xbe, 0x104)[0]

# Read current library version table info
lib_count  = struct.unpack_from('<I', xbe, 0x160)[0]
lib_va     = struct.unpack_from('<I', xbe, 0x164)[0]
lib_offset = lib_va - base_addr  # File offset of the table

print("  Current library count: %d" % lib_count)
print("  Library table VA: 0x%08X (file offset 0x%X)" % (lib_va, lib_offset))

# Read existing entries to get the build number
if lib_count > 0:
    first_entry = xbe[lib_offset:lib_offset+16]
    existing_build = struct.unpack_from('<H', first_entry, 12)[0]
else:
    existing_build = 5849
print("  Using build number: %d" % existing_build)

# Build the two new 16-byte library version entries
# Format: 8-char name (padded with nulls) + WORD major + WORD minor + WORD build + WORD flags
def make_lib_entry(name, build, flags=0x4001):
    name_bytes = name.encode('ascii')[:8].ljust(8, b'\x00')
    return name_bytes + struct.pack('<HHHH', 1, 0, build, flags)

d3d8_entry    = make_lib_entry('D3D8',    existing_build)
xgraphc_entry = make_lib_entry('XGRAPHC', existing_build)

# Strategy: append the new entries right after the existing table,
# then update the count. This works because imagebld leaves padding
# or we can safely extend into the space after the table.
#
# First check what's after the current table
table_end = lib_offset + lib_count * 16
bytes_after = xbe[table_end:table_end+32]
print("  Bytes after table: %s" % bytes_after.hex())

# We need 32 bytes (2 entries). Append at end of file and update pointers.
# Actually, the safest approach: append new entries to end of XBE file,
# then rewrite the header to point to a new combined table there.

# Build complete new library table: existing entries + D3D8 + XGRAPHC
new_entries = bytearray()
for i in range(lib_count):
    off = lib_offset + i * 16
    new_entries += xbe[off:off+16]
new_entries += d3d8_entry
new_entries += xgraphc_entry
new_count = lib_count + 2

# Align file size to 4 bytes before appending
while len(xbe) % 4 != 0:
    xbe.append(0)

# New table goes at end of file
new_table_file_offset = len(xbe)
new_table_va = new_table_file_offset + base_addr

# Append the new table
xbe += new_entries

# Update header: count and table pointer
struct.pack_into('<I', xbe, 0x160, new_count)
struct.pack_into('<I', xbe, 0x164, new_table_va)

# Update kernel and XAPI library version pointers to point into new table
# XAPI is entry[0], kernel is the XBOXKRNL entry
for i in range(new_count):
    off = new_table_file_offset + i * 16
    name = xbe[off:off+8].rstrip(b'\x00').decode('ascii', errors='replace')
    entry_va = new_table_va + i * 16
    if name.startswith('XAPILIB'):
        struct.pack_into('<I', xbe, 0x16C, entry_va)
        print("  XAPI lib version -> entry[%d] VA 0x%08X" % (i, entry_va))
    elif name == 'XBOXKRNL':
        struct.pack_into('<I', xbe, 0x168, entry_va)
        print("  Kernel lib version -> entry[%d] VA 0x%08X" % (i, entry_va))

print("  New library count: %d" % new_count)
print("  New table VA: 0x%08X (file offset 0x%X)" % (new_table_va, new_table_file_offset))

# Print final table
for i in range(new_count):
    off = new_table_file_offset + i * 16
    name = xbe[off:off+8].rstrip(b'\x00').decode('ascii', errors='replace')
    major, minor, build, flags = struct.unpack_from('<HHHH', xbe, off + 8)
    print("  [%d] %-8s v%d.%d.%d flags=0x%04X" % (i, name, major, minor, build, flags))

with open(xbe_path, 'wb') as f:
    f.write(xbe)

print("XBE patched successfully.")
